// ENCAPSULATION(OOPS)

// ENCAPSULATION IS WRAPPING UP OF DATA AND MEMBER FUNCTIONS IN A SINGLE UNIT CALLED CLASS.

// ENCAPSULATION HELPS IN DATA HIDING BY USING PRIVATE ACCESS SPECIFIER LIKE IN BANK ACCOUNTS THERE ARE SOME PROPERTIES THST SHOUL BE KEPT PRIVATE